name: Temporary job to test all steps to install kind, vault & crossplane

on:
  workflow_dispatch:
  push:
    branches: [ dummy ]
    paths-ignore:
      - 'scripts/**'    # Ignores bash scripts
      - '*.md'          # Ignores .md files at the root of the repository
      - '**/*.md'       # Ignores .md files within subdirectories

env:
  # Variable used to disable the pv tool which is not working here as pseudo tty is not supported by GitHub steps
  PSEUDO_TTY: "false"

jobs:
  setup-primaza-k8s-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Setup Kubernetes using kind and deploy a local container registry
        env:
          REGISTRY_NAME: kind-registry
          REGISTRY_PORT: 5000
        run: |
          curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install
          
          # Adding registry name to the /etc/hosts file
          echo "127.0.0.1 $REGISTRY_NAME" | sudo tee -a /etc/hosts

          # Exporting the registry location for subsequent jobs
          echo "KIND_REGISTRY=${REGISTRY_NAME}:${REGISTRY_PORT}" >> $GITHUB_ENV

      - name: Build primaza, generate image, Helm chart and push image
        env:
          REGISTRY_GROUP: local

          PRIMAZA_GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          GITHUB_SHA_COMMIT: ${{ github.sha }}
          PRIMAZA_IMAGE_NAME: $KIND_REGISTRY/local/primaza-app
          PRIMAZA_NAMESPACE: primaza

          PRIMAZA_URL: primaza.127.0.0.1.nip.io
          # Variable needed by the helm chart to configure primaza vault client
          VAULT_URL: http://vault-internal.vault:8200
        run: |
          ./scripts/primaza.sh build

      - name: Deploy primaza helm chart
        env:
          PRIMAZA_URL: primaza.127.0.0.1.nip.io
          PRIMAZA_IMAGE_NAME: $KIND_REGISTRY/local/primaza-app
          PRIMAZA_NAMESPACE: primaza
          # Variable needed by the helm chart to configure primaza vault client
          VAULT_URL: http://vault-internal.vault:8200
        run: |
          bash ./scripts/primaza.sh localdeploy
          bash ./scripts/primaza.sh isAlive

      - name: Load the data such as cluster, services & credentials
        env:
          PRIMAZA_URL: primaza.127.0.0.1.nip.io
          PRIMAZA_NAMESPACE: primaza
        run: |
          bash ./scripts/primaza.sh loaddata

      - name: Installing Vault
        run: |
          bash ./scripts/vault.sh

      - name: Installing Crossplane
        run: |
          bash ./scripts/crossplane.sh

      - name: Installing Postgresql DB and Atomic fruits
        env:
          ATOMIC_FRUITS_NAMESPACE: app
        run: |
          bash ./scripts/atomic-fruits.sh
          
          # Wait till postgresql pod is ready
          kubectl wait -n $ATOMIC_FRUITS_NAMESPACE pod/postgresql-0 --for=condition=ready --timeout=300s

      - name: Creating the Primaza fruits Vault KV key
        run: |
          source ./scripts/toolbox.sh
          
          # Login as user bob and password sinclair
          bash ./scripts/vault.sh loginAsUser bob sinclair
          
          # Register the primaza KV entries
          note "vault kv put -mount=secret primaza/fruits username=healthy password=healthy database=fruits_database"
          ./scripts/vault.sh vaultExec "vault kv put -mount=secret primaza/fruits username=healthy password=healthy database=fruits_database"

      - name: Wait until atomic-fruits is registered in Primaza
        env:
          PRIMAZA_URL: primaza.127.0.0.1.nip.io
        run: |
          source ./scripts/toolbox.sh
          max_retries=5
          retry_delay=5
          retry_attempt=1

          function discover_atomic_fruits() {
            APPLICATION=$(curl -H 'Accept: application/json' -s "$PRIMAZA_URL/applications/name/atomic-fruits")
            if [[ $(echo "$APPLICATION" | jq -r '.name') == "atomic-fruits" ]]; then
              return 0
            else
              return 1
            fi
          }
          
          while [ $retry_attempt -le $max_retries ]; do
            note "Attempt $retry_attempt of $max_retries"
            if discover_atomic_fruits; then
              note "Primaza discovered the atomic-fruits application: $APPLICATION."
              exit 0
            else
              warn "Primaza didn't yet discovered the atomic-fruits application: $APPLICATION."
              sleep $retry_delay
            fi
          done

      - name: Bind application
        env:
          PRIMAZA_URL: primaza.127.0.0.1.nip.io
          PRIMAZA_NAMESPACE: primaza
        run: |
          bash ./scripts/primaza.sh bindApplication atomic-fruits fruits-claim

      - id: wait-for-atomic-fruits
        name: atomic-fruits should now be up and running
        env:
          PRIMAZA_URL: primaza.127.0.0.1.nip.io
          ATOMIC_FRUITS_NAMESPACE: app
        run: |
          source ./scripts/toolbox.sh
          
          # When the condition met and that the atomic fruits deployment is available, 
          # that means that the application is now bound with the service, 
          # so we're good !
          kubectl wait --timeout=300s --for=condition=available deployment atomic-fruits -n $ATOMIC_FRUITS_NAMESPACE
          
          CLAIM_STATUS=$(curl -s http://$PRIMAZA_URL/claims/name/fruits-claim | jq -r .status)
          if [[ "$CLAIM_STATUS" == "bound" ]]; then
            exit 0
          else
            error "Status of the claim: fruits-claim is: $CLAIM_STATUS" 
            exit 1
          fi

      - name: (Only if it failed) Log Primaza traces at failures
        if: failure()
        run: |
          bash ./scripts/primaza.sh log

      - name: (Only if it failed) Log Atomic Fruits traces at failures
        if: failure()
        env:
          ATOMIC_FRUITS_NAMESPACE: app
        run: |
          source ./scripts/toolbox.sh
          
          log BLUE "List of the pods deployed on the cluster"
          kubectl get pods -A
          
          log BLUE "Description of the atomic-fruits deployment resource"
          kubectl get deployment atomic-fruits -o yaml -n $ATOMIC_FRUITS_NAMESPACE
          
          log BLUE "Logs of the atomic-fruits deployment resource"
          kubectl logs deploy/atomic-fruits --all-containers=true -n $ATOMIC_FRUITS_NAMESPACE
          
          POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=atomic-fruits -n $ATOMIC_FRUITS_NAMESPACE -o name)
          log BLUE "Information of the Atomic-fruits pod"
          kubectl describe $POD_NAME -n $ATOMIC_FRUITS_NAMESPACE
          
          log BLUE "Logs of atomic-fruits running pod"
          kubectl logs $POD_NAME -n $ATOMIC_FRUITS_NAMESPACE
          
          log BLUE "Logs of atomic-fruits terminated pod"
          kubectl logs -p $POD_NAME -n $ATOMIC_FRUITS_NAMESPACE
          
          
          
